# Generated by Django 5.1.1 on 2024-10-27 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('display', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'directory',
                'verbose_name_plural': 'directories',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=255)),
                ('endpoint', models.URLField(blank=True, help_text='The URL endpoint for the AI', validators=[django.core.validators.URLValidator()])),
                ('encrypted_api_key', models.BinaryField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, help_text='Arbitrary key-value pairs for model parameters', null=True)),
                ('dirnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aimodels', to='yesand.dirnode')),
            ],
            options={
                'verbose_name': 'AI model',
                'verbose_name_plural': 'AI models',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('aimodels', models.ManyToManyField(blank=True, related_name='prompts', to='yesand.aimodel')),
                ('dirnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='yesand.dirnode')),
                ('fields', models.ManyToManyField(blank=True, related_name='prompts', to='yesand.field')),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'prompts',
            },
        ),
    ]
