name: Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Trigger release workflow
        if: steps.tag_version.outputs.new_tag != ''
        uses: yakubique/trigger-github-workflow@v1
        with:
          repository: ${{ github.repository }}
          workflow: release.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          params: |
            {
              "version": "${{ steps.tag_version.outputs.tag }}"
            }